function parsave_event_ilandscape(savefname,consumerstats,vacstats,BUILDTIME,VACLAND,LANDVALUE,...
    AVGRENT,RETURN,LOTTYPE,BASELAYER,Rpop,Rvacrate,Rvaclots,numlt,Rleftoverpop,...
    avgrentdynms,rentdynstats,farmsoldinfo,avgrent,avgfarmsize,stdfarmsize,...
    DELTA,survivalrate,LOCWGHT,REGWGHT,PCTSEARCH,zeta,HIBETA,MIDBETA,LOWBETA,...
    POPGROW,ccost,newhouseset,bidtot,meandisp,maxdevdist,setupmap,...
    vacrate,Farminfo,oldincome,Realreturn,Realavgret,Exptrentdiff,...
    Avgexptdiff,htincome,numtotbids,totfarmrecord,htperyear,Newbidlevel,...
    totbrokerrecord,Farmdist2dev,Bprojmap,Bmodelmap,WTAlandmap,WTPlandmap,...
    Landprojmap,Landmodmap,bidshare,buildshare,landdemand,EXPTHOUSE,lotchoice,...
    Exptprofit,Exptret,Realexptret,Realavgexptret,idealset,profset,...
    avgbrokervar,carrycost,Lottype,CONINFO,PREFMAP,IMPACT,DAMAGE,LANDINFO,...
    lotlocate,relocated,reloc_stats,conidmap,subjriskmap,stormoccur,...
    LOTRENT,LOTCON,LOTINC,LOTINS,leave_stats,decisiondata,regmoveouts,...
    vacantlist,TAXREV)

cd C:\Users\nrmagliocca\'Box Sync'\'Data Drive'\model_results\CHALMS_event_ilandscape_vartax_060718

save(savefname,...
    'consumerstats','vacstats','BUILDTIME','VACLAND','LANDVALUE',...
    'AVGRENT','RETURN','LOTTYPE','BASELAYER','Rpop','Rvacrate','Rvaclots','numlt','Rleftoverpop',...
    'avgrentdynms','rentdynstats','farmsoldinfo','avgrent','avgfarmsize','stdfarmsize',...
    'DELTA','survivalrate','LOCWGHT','REGWGHT','PCTSEARCH','zeta','HIBETA','MIDBETA','LOWBETA',...
    'POPGROW','ccost','newhouseset','bidtot','meandisp','maxdevdist','setupmap',...
    'vacrate','Farminfo','oldincome','Realreturn','Realavgret','Exptrentdiff',...
    'Avgexptdiff','htincome','numtotbids','totfarmrecord','htperyear','Newbidlevel',...
    'totbrokerrecord','Farmdist2dev','Bprojmap','Bmodelmap','WTAlandmap','WTPlandmap',...
    'Landprojmap','Landmodmap','bidshare','buildshare','landdemand','EXPTHOUSE','lotchoice',...
    'Exptprofit','Exptret','Realexptret','Realavgexptret','idealset','profset',...
    'avgbrokervar','carrycost','Lottype','CONINFO','PREFMAP','IMPACT','DAMAGE','LANDINFO',...
    'lotlocate','relocated','reloc_stats','conidmap','subjriskmap','stormoccur',...
    'LOTRENT','LOTCON','LOTINC','LOTINS','leave_stats','decisiondata','regmoveouts',...
    'vacantlist','TAXREV')
        
cd C:\Users\nrmagliocca\'Box Sync'\'Data Drive'\CHALMS_coast\simple-chalms
end
        
        